image: archlinux
packages:
  - base-devel
  - clang
  - dbus
sources:
  - https://git.sr.ht/~mariusor/mpris-ctl
tasks:
  - build: |
      cd mpris-ctl
      make check
      ## this needs libdbus and glibc to be built with the memory sanitizer, which is out of scope for the moment
      #make CC=clang check
